input_scanners:
  PromptInjection:
    enabled: false
    params:
      threshold: 0.85
      use_onnx: true
  Secrets:
    enabled: true
    params: {}
  Anonymize:
    enabled: false
    params:
      use_onnx: true

output_scanners:
  Toxicity:
    enabled: false
    params:
      threshold: 0.92
      use_onnx: true
  MaliciousURLs:
    enabled: false
    params: {}
  Sensitive:
    enabled: false
    params:
      threshold: 0.50
  Deanonymize:
    enabled: false
    params:
      use_onnx: false